### ISSUE TITLE
Polar LSL -> HRV decomposition

### ISSUE THREAD

**Issue by sunshineinsandiego** [markspan/PolarBand2lsl#3]
Hi there - Wondering if you had any advice for calculating the HRV (LF and HF) off of the LSL stream that your code pulls from an H10 polar band? Thanks!

**Comment by markspan** [comment]
I like to refer to:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5624990/

First determine the R-tops from the signal using the MATLAB code in this package! The interpolation used in the code is necessary if you want to obtain valid variability measures.

**Comment by sunshineinsandiego** [comment]
Terrific, thanks Mark!
